version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/*'
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
        patterns:
          - '*'
      production-dependencies:
        dependency-type: production
        patterns:
          - '*'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
