version: '0.2'
language: en
enableGlobDot: true
languageSettings:
  - languageId: yaml,markdown
    substitutions:
      - ["''", "'"]
dictionaries:
  - typescript
  - node
  - npm
  - fonts
  - html
  - css
  - misc
ignorePaths:
  - node_modules
  - fixtures
  - dist
  - dist-test
  - coverage
  - pnpm-lock.yaml
  - '**/*.log'
  - CHANGELOG.md
  - .git/!(hooks,COMMIT_EDITMSG)
  - test-packages/*/tests
  - test-packages/*/__snapshots
words:
  - COMMIT_EDITMSG
  - dedup
  - gitdir
  - heredocs
  - inlines
  - Precomputes
  - prebuilds
  - sigstore
  - unaliased
  - unpadded
  - worktrees
ignoreWords:
  - .mtsx
  - parsedTexts
