version: '0.2'
language: en
enableGlobDot: true
dictionaries:
  - typescript
  - node
  - npm
  - fonts
  - html
  - css
  - misc
ignorePaths:
  - node_modules
  - fixtures
  - dist
  - dist-test
  - coverage
  - pnpm-lock.yaml
  - '**/*.log'
  - CHANGELOG.md
  - .git/!(hooks,COMMIT_EDITMSG)
words:
  - COMMIT_EDITMSG
  - dedup
  - inlines
  - sigstore
  - unaliased
