packages:
  - packages/*
  - packages/*/samples

blockExoticSubdeps: true

catalog:
  '@cspell/cspell-types': ^10.3.2
  cspell: ^10.3.2

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@cspell/*'
  - cspell
  - cspell-*

nodeLinker: isolated

onlyBuiltDependencies:
  - tree-sitter
  - tree-sitter-javascript
  - tree-sitter-typescript

saveWorkspaceProtocol: rolling

trustPolicy: no-downgrade

trustPolicyExclude:
  - undici-types@6.21.0
  - semver@5.7.2
