packages:
  - packages/*
  - packages/*/samples
  - scripts
  - test-packages/*

allowBuilds:
  tree-sitter: true
  tree-sitter-javascript: true
  tree-sitter-typescript: true

blockExoticSubdeps: true

catalog:
  '@cspell/cspell-types': ^10.3.3
  cspell: ^10.3.3

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@cspell/*'
  - cspell
  - cspell-*

nodeLinker: isolated

saveWorkspaceProtocol: rolling

trustPolicy: no-downgrade

trustPolicyExclude:
  - undici-types@6.21.0
  - semver@5.7.2
